### ISSUE TITLE
Crashes MuseScore 4

### ISSUE THREAD

**Issue by Jabrwock** [Meerkatenator/mpb#17]
To replicate, enable and run on MuseScore 4.02

**Comment by Meerkatenator** [comment]
Unfortunately many things changed from MU3.6 to MU4 (including support for extensions), and I haven’t had time to port MPB over. If you download MU3.6 (legacy), then you can use MPB with that version.

**Comment by Jojo-Schmitz** [comment]
Fixing the crash is dead easy: just change the `Qt.quit();` to just `quit();`
And with a tiny bit of additional code it also shows in the menu:
```cpp
...
      requiresScore: true

      Component.onCompleted : {
            if (mscoreMajorVersion >= 4) {
                  title = qsTr("PB_OTB") ;
                  // thumbnailName = ".png";
                  // categoryCode = "some_category";
            }
      }

      property var the_note : null;  
...
 ```

**Comment by Meerkatenator** [comment]
This plugin now runs in MU4 (aka doesn't crash) but may not be relevant anymore due to playback improvements in MU4.
